# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# - task: JFrogMaven@1
#   inputs:
#     mavenPomFile: 'pom.xml'
#     goals: 'install'
#     artifactoryResolverService: 'art1'
#     targetResolveReleaseRepo: 'maven-virtual'
#     targetResolveSnapshotRepo: 'maven-virtual'
#     artifactoryDeployService: 'art1'
#     targetDeployReleaseRepo: 'maven-dev-local'
#     targetDeploySnapshotRepo: 'maven-dev-local'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.11'


- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false